<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('countries')->delete();
        
        \DB::table('countries')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Andorra',
                'code' => 'AD',
                'iso3' => 'AND',
                'currency' => 'EUR',
                'languages' => 'ca',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'United Arab Emirates',
                'code' => 'AE',
                'iso3' => 'ARE',
                'currency' => 'AED',
                'languages' => 'ar-AE,fa,en,hi,ur',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Afghanistan',
                'code' => 'AF',
                'iso3' => 'AFG',
                'currency' => 'AFN',
                'languages' => 'fa-AF,ps,uz-AF,tk',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Antigua and Barbuda',
                'code' => 'AG',
                'iso3' => 'ATG',
                'currency' => 'XCD',
                'languages' => 'en-AG',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Anguilla',
                'code' => 'AI',
                'iso3' => 'AIA',
                'currency' => 'XCD',
                'languages' => 'en-AI',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Albania',
                'code' => 'AL',
                'iso3' => 'ALB',
                'currency' => 'ALL',
                'languages' => 'sq,el',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Armenia',
                'code' => 'AM',
                'iso3' => 'ARM',
                'currency' => 'AMD',
                'languages' => 'hy',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Angola',
                'code' => 'AO',
                'iso3' => 'AGO',
                'currency' => 'AOA',
                'languages' => 'pt-AO',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Antarctica',
                'code' => 'AQ',
                'iso3' => 'ATA',
                'currency' => '',
                'languages' => '',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Argentina',
                'code' => 'AR',
                'iso3' => 'ARG',
                'currency' => 'ARS',
                'languages' => 'es-AR,en,it,de,fr,gn',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'American Samoa',
                'code' => 'AS',
                'iso3' => 'ASM',
                'currency' => 'USD',
                'languages' => 'en-AS,sm,to',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Austria',
                'code' => 'AT',
                'iso3' => 'AUT',
                'currency' => 'EUR',
                'languages' => 'de-AT,hr,hu,sl',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Australia',
                'code' => 'AU',
                'iso3' => 'AUS',
                'currency' => 'AUD',
                'languages' => 'en-AU',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Aruba',
                'code' => 'AW',
                'iso3' => 'ABW',
                'currency' => 'AWG',
                'languages' => 'nl-AW,es,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Åland Islands',
                'code' => 'AX',
                'iso3' => 'ALA',
                'currency' => 'EUR',
                'languages' => 'sv-AX',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Azerbaijan',
                'code' => 'AZ',
                'iso3' => 'AZE',
                'currency' => 'AZN',
                'languages' => 'az,ru,hy',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Bosnia and Herzegovina',
                'code' => 'BA',
                'iso3' => 'BIH',
                'currency' => 'BAM',
                'languages' => 'bs,hr-BA,sr-BA',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Barbados',
                'code' => 'BB',
                'iso3' => 'BRB',
                'currency' => 'BBD',
                'languages' => 'en-BB',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Bangladesh',
                'code' => 'BD',
                'iso3' => 'BGD',
                'currency' => 'BDT',
                'languages' => 'bn-BD,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Belgium',
                'code' => 'BE',
                'iso3' => 'BEL',
                'currency' => 'EUR',
                'languages' => 'nl-BE,fr-BE,de-BE',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Burkina Faso',
                'code' => 'BF',
                'iso3' => 'BFA',
                'currency' => 'XOF',
                'languages' => 'fr-BF',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Bulgaria',
                'code' => 'BG',
                'iso3' => 'BGR',
                'currency' => 'BGN',
                'languages' => 'bg,tr-BG,rom',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Bahrain',
                'code' => 'BH',
                'iso3' => 'BHR',
                'currency' => 'BHD',
                'languages' => 'ar-BH,en,fa,ur',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Burundi',
                'code' => 'BI',
                'iso3' => 'BDI',
                'currency' => 'BIF',
                'languages' => 'fr-BI,rn',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Benin',
                'code' => 'BJ',
                'iso3' => 'BEN',
                'currency' => 'XOF',
                'languages' => 'fr-BJ',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Saint Barthélemy',
                'code' => 'BL',
                'iso3' => 'BLM',
                'currency' => 'EUR',
                'languages' => 'fr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Bermuda',
                'code' => 'BM',
                'iso3' => 'BMU',
                'currency' => 'BMD',
                'languages' => 'en-BM,pt',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Brunei Darussalam',
                'code' => 'BN',
                'iso3' => 'BRN',
                'currency' => 'BND',
                'languages' => 'ms-BN,en-BN',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Bolivia',
                'code' => 'BO',
                'iso3' => 'BOL',
                'currency' => 'BOB',
                'languages' => 'es-BO,qu,ay',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Bonaire, Sint Eustatius and Saba',
                'code' => 'BQ',
                'iso3' => 'BES',
                'currency' => 'USD',
                'languages' => 'nl,pap,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Brazil',
                'code' => 'BR',
                'iso3' => 'BRA',
                'currency' => 'BRL',
                'languages' => 'pt-BR,es,en,fr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Bahamas',
                'code' => 'BS',
                'iso3' => 'BHS',
                'currency' => 'BSD',
                'languages' => 'en-BS',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Bhutan',
                'code' => 'BT',
                'iso3' => 'BTN',
                'currency' => 'BTN',
                'languages' => 'dz',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Bouvet Island',
                'code' => 'BV',
                'iso3' => 'BVT',
                'currency' => 'NOK',
                'languages' => '',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Botswana',
                'code' => 'BW',
                'iso3' => 'BWA',
                'currency' => 'BWP',
                'languages' => 'en-BW,tn-BW',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Belarus',
                'code' => 'BY',
                'iso3' => 'BLR',
                'currency' => 'BYR',
                'languages' => 'be,ru',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Belize',
                'code' => 'BZ',
                'iso3' => 'BLZ',
                'currency' => 'BZD',
                'languages' => 'en-BZ,es',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Canada',
                'code' => 'CA',
                'iso3' => 'CAN',
                'currency' => 'CAD',
                'languages' => 'en-CA,fr-CA,iu',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Cocos [Keeling] Islands',
                'code' => 'CC',
                'iso3' => 'CCK',
                'currency' => 'AUD',
                'languages' => 'ms-CC,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Democratic Republic of the Congo',
                'code' => 'CD',
                'iso3' => 'COD',
                'currency' => 'COD',
                'languages' => 'fr-CD,ln,kg',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Central African Republic',
                'code' => 'CF',
                'iso3' => 'CAF',
                'currency' => 'XAF',
                'languages' => 'fr-CF,sg,ln,kg',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Republic of the Congo',
                'code' => 'CG',
                'iso3' => 'COG',
                'currency' => 'XAF',
                'languages' => 'fr-CG,kg,ln-CG',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Switzerland',
                'code' => 'CH',
                'iso3' => 'CHE',
                'currency' => 'CHF',
                'languages' => 'de-CH,fr-CH,it-CH,rm',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Ivory Coast',
                'code' => 'CI',
                'iso3' => 'CIV',
                'currency' => 'XOF',
                'languages' => 'fr-CI',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Cook Islands',
                'code' => 'CK',
                'iso3' => 'COK',
                'currency' => 'NZD',
                'languages' => 'en-CK,mi',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Chile',
                'code' => 'CL',
                'iso3' => 'CHL',
                'currency' => 'CLP',
                'languages' => 'es-CL',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Cameroon',
                'code' => 'CM',
                'iso3' => 'CMR',
                'currency' => 'XAF',
                'languages' => 'en-CM,fr-CM',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'China',
                'code' => 'CN',
                'iso3' => 'CHN',
                'currency' => 'CNY',
                'languages' => 'zh-CN,yue,wuu,dta,ug,za',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Colombia',
                'code' => 'CO',
                'iso3' => 'COL',
                'currency' => 'COP',
                'languages' => 'es-CO',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Costa Rica',
                'code' => 'CR',
                'iso3' => 'CRI',
                'currency' => 'CRC',
                'languages' => 'es-CR,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Cuba',
                'code' => 'CU',
                'iso3' => 'CUB',
                'currency' => 'CUP',
                'languages' => 'es-CU',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Cape Verde',
                'code' => 'CV',
                'iso3' => 'CPV',
                'currency' => 'CVE',
                'languages' => 'pt-CV',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Curaçao',
                'code' => 'CW',
                'iso3' => 'CUW',
                'currency' => 'ANG',
                'languages' => 'nl,pap',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Christmas Island',
                'code' => 'CX',
                'iso3' => 'CXR',
                'currency' => 'AUD',
                'languages' => 'en,zh,ms-CC',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Cyprus',
                'code' => 'CY',
                'iso3' => 'CYP',
                'currency' => 'EUR',
                'languages' => 'el-CY,tr-CY,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Czech Republic',
                'code' => 'CZ',
                'iso3' => 'CZE',
                'currency' => 'CZK',
                'languages' => 'cs,sk',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Germany',
                'code' => 'DE',
                'iso3' => 'DEU',
                'currency' => 'EUR',
                'languages' => 'de',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Djibouti',
                'code' => 'DJ',
                'iso3' => 'DJI',
                'currency' => 'DJF',
                'languages' => 'fr-DJ,ar,so-DJ,aa',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Denmark',
                'code' => 'DK',
                'iso3' => 'DNK',
                'currency' => 'DKK',
                'languages' => 'da-DK,en,fo,de-DK',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Dominica',
                'code' => 'DM',
                'iso3' => 'DMA',
                'currency' => 'XCD',
                'languages' => 'en-DM',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Dominican Republic',
                'code' => 'DO',
                'iso3' => 'DOM',
                'currency' => 'DOP',
                'languages' => 'es-DO',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Algeria',
                'code' => 'DZ',
                'iso3' => 'DZA',
                'currency' => 'DZD',
                'languages' => 'ar-DZ',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Ecuador',
                'code' => 'EC',
                'iso3' => 'ECU',
                'currency' => 'USD',
                'languages' => 'es-EC',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'Estonia',
                'code' => 'EE',
                'iso3' => 'EST',
                'currency' => 'EUR',
                'languages' => 'et,ru',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'Egypt',
                'code' => 'EG',
                'iso3' => 'EGY',
                'currency' => 'EGP',
                'languages' => 'ar-EG,en,fr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'Western Sahara',
                'code' => 'EH',
                'iso3' => 'ESH',
                'currency' => 'MAD',
                'languages' => 'ar,mey',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'Eritrea',
                'code' => 'ER',
                'iso3' => 'ERI',
                'currency' => 'ERN',
                'languages' => 'aa-ER,ar,tig,kun,ti-ER',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'Spain',
                'code' => 'ES',
                'iso3' => 'ESP',
                'currency' => 'EUR',
                'languages' => 'es-ES,ca,gl,eu,oc',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'Ethiopia',
                'code' => 'ET',
                'iso3' => 'ETH',
                'currency' => 'ETB',
                'languages' => 'am,en-ET,om-ET,ti-ET,so-ET,sid',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'Finland',
                'code' => 'FI',
                'iso3' => 'FIN',
                'currency' => 'EUR',
                'languages' => 'fi-FI,sv-FI,smn',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'Fiji',
                'code' => 'FJ',
                'iso3' => 'FJI',
                'currency' => 'FJD',
                'languages' => 'en-FJ,fj',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'Falkland Islands',
                'code' => 'FK',
                'iso3' => 'FLK',
                'currency' => 'FKP',
                'languages' => 'en-FK',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'Micronesia',
                'code' => 'FM',
                'iso3' => 'FSM',
                'currency' => 'USD',
                'languages' => 'en-FM,chk,pon,yap,kos,uli,woe,nkr,kpg',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'Faroe Islands',
                'code' => 'FO',
                'iso3' => 'FRO',
                'currency' => 'DKK',
                'languages' => 'fo,da-FO',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'France',
                'code' => 'FR',
                'iso3' => 'FRA',
                'currency' => 'EUR',
                'languages' => 'fr-FR,frp,br,co,ca,eu,oc',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'Gabon',
                'code' => 'GA',
                'iso3' => 'GAB',
                'currency' => 'XAF',
                'languages' => 'fr-GA',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'United Kingdom of Great Britain and Northern Ireland',
                'code' => 'GB',
                'iso3' => 'GBR',
                'currency' => 'GBP',
                'languages' => 'en-GB,cy-GB,gd',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'Grenada',
                'code' => 'GD',
                'iso3' => 'GRD',
                'currency' => 'XCD',
                'languages' => 'en-GD',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'Georgia',
                'code' => 'GE',
                'iso3' => 'GEO',
                'currency' => 'GEL',
                'languages' => 'ka,ru,hy,az',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'French Guiana',
                'code' => 'GF',
                'iso3' => 'GUF',
                'currency' => 'EUR',
                'languages' => 'fr-GF',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'Guernsey',
                'code' => 'GG',
                'iso3' => 'GGY',
                'currency' => 'GBP',
                'languages' => 'en,fr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'Ghana',
                'code' => 'GH',
                'iso3' => 'GHA',
                'currency' => 'GHS',
                'languages' => 'en-GH,ak,ee,tw',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'Gibraltar',
                'code' => 'GI',
                'iso3' => 'GIB',
                'currency' => 'GIP',
                'languages' => 'en-GI,es,it,pt',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'Greenland',
                'code' => 'GL',
                'iso3' => 'GRL',
                'currency' => 'DKK',
                'languages' => 'kl,da-GL,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'Gambia',
                'code' => 'GM',
                'iso3' => 'GMB',
                'currency' => 'GMD',
                'languages' => 'en-GM,mnk,wof,wo,ff',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'Guinea',
                'code' => 'GN',
                'iso3' => 'GIN',
                'currency' => 'GNF',
                'languages' => 'fr-GN',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'Guadeloupe',
                'code' => 'GP',
                'iso3' => 'GLP',
                'currency' => 'EUR',
                'languages' => 'fr-GP',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'Equatorial Guinea',
                'code' => 'GQ',
                'iso3' => 'GNQ',
                'currency' => 'XAF',
                'languages' => 'es-GQ,fr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'Greece',
                'code' => 'GR',
                'iso3' => 'GRC',
                'currency' => 'EUR',
                'languages' => 'el-GR,en,fr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'South Georgia and the South Sandwich Islands',
                'code' => 'GS',
                'iso3' => 'SGS',
                'currency' => 'GBP',
                'languages' => 'en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'Guatemala',
                'code' => 'GT',
                'iso3' => 'GTM',
                'currency' => 'GTQ',
                'languages' => 'es-GT',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'Guam',
                'code' => 'GU',
                'iso3' => 'GUM',
                'currency' => 'USD',
                'languages' => 'en-GU,ch-GU',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'Guinea-Bissau',
                'code' => 'GW',
                'iso3' => 'GNB',
                'currency' => 'XOF',
                'languages' => 'pt-GW,pov',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'Guyana',
                'code' => 'GY',
                'iso3' => 'GUY',
                'currency' => 'GYD',
                'languages' => 'en-GY',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'Hong Kong',
                'code' => 'HK',
                'iso3' => 'HKG',
                'currency' => 'HKD',
                'languages' => 'zh-HK,yue,zh,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'Heard Island and McDonald Islands',
                'code' => 'HM',
                'iso3' => 'HMD',
                'currency' => 'AUD',
                'languages' => '',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'Honduras',
                'code' => 'HN',
                'iso3' => 'HND',
                'currency' => 'HNL',
                'languages' => 'es-HN',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'Croatia',
                'code' => 'HR',
                'iso3' => 'HRV',
                'currency' => 'HRK',
                'languages' => 'hr-HR,sr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'Haiti',
                'code' => 'HT',
                'iso3' => 'HTI',
                'currency' => 'HTG',
                'languages' => 'ht,fr-HT',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'Hungary',
                'code' => 'HU',
                'iso3' => 'HUN',
                'currency' => 'HUF',
                'languages' => 'hu-HU',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'name' => 'Indonesia',
                'code' => 'ID',
                'iso3' => 'IDN',
                'currency' => 'IDR',
                'languages' => 'id,en,nl,jv',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'name' => 'Ireland',
                'code' => 'IE',
                'iso3' => 'IRL',
                'currency' => 'EUR',
                'languages' => 'en-IE,ga-IE',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'name' => 'Israel',
                'code' => 'IL',
                'iso3' => 'ISR',
                'currency' => 'ILS',
                'languages' => 'he,ar-IL,en-IL,',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'name' => 'Isle of Man',
                'code' => 'IM',
                'iso3' => 'IMN',
                'currency' => 'GBP',
                'languages' => 'en,gv',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'name' => 'India',
                'code' => 'IN',
                'iso3' => 'IND',
                'currency' => 'INR',
                'languages' => 'en-IN,hi,bn,te,mr,ta,ur,gu,kn,ml,or,pa,as,bh,sat,ks,ne,sd,kok,doi,mni,sit,sa,fr,lus,inc',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'name' => 'British Indian Ocean Territory',
                'code' => 'IO',
                'iso3' => 'IOT',
                'currency' => 'USD',
                'languages' => 'en-IO',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'name' => 'Iraq',
                'code' => 'IQ',
                'iso3' => 'IRQ',
                'currency' => 'IQD',
                'languages' => 'ar-IQ,ku,hy',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'name' => 'Iran',
                'code' => 'IR',
                'iso3' => 'IRN',
                'currency' => 'IRR',
                'languages' => 'fa-IR,ku',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'name' => 'Iceland',
                'code' => 'IS',
                'iso3' => 'ISL',
                'currency' => 'ISK',
                'languages' => 'is,en,de,da,sv,no',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'name' => 'Italy',
                'code' => 'IT',
                'iso3' => 'ITA',
                'currency' => 'EUR',
                'languages' => 'it-IT,de-IT,fr-IT,sc,ca,co,sl',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'name' => 'Jersey',
                'code' => 'JE',
                'iso3' => 'JEY',
                'currency' => 'GBP',
                'languages' => 'en,pt',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'name' => 'Jamaica',
                'code' => 'JM',
                'iso3' => 'JAM',
                'currency' => 'JMD',
                'languages' => 'en-JM',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'name' => 'Jordan',
                'code' => 'JO',
                'iso3' => 'JOR',
                'currency' => 'JOD',
                'languages' => 'ar-JO,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'name' => 'Japan',
                'code' => 'JP',
                'iso3' => 'JPN',
                'currency' => 'JPY',
                'languages' => 'ja',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'name' => 'Kenya',
                'code' => 'KE',
                'iso3' => 'KEN',
                'currency' => 'KES',
                'languages' => 'en-KE,sw-KE',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'name' => 'Kyrgyzstan',
                'code' => 'KG',
                'iso3' => 'KGZ',
                'currency' => 'KGS',
                'languages' => 'ky,uz,ru',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'name' => 'Cambodia',
                'code' => 'KH',
                'iso3' => 'KHM',
                'currency' => 'KHR',
                'languages' => 'km,fr,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'name' => 'Kiribati',
                'code' => 'KI',
                'iso3' => 'KIR',
                'currency' => 'AUD',
                'languages' => 'en-KI,gil',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'name' => 'Comoros',
                'code' => 'KM',
                'iso3' => 'COM',
                'currency' => 'KMF',
                'languages' => 'ar,fr-KM',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'name' => 'Saint Kitts and Nevis',
                'code' => 'KN',
                'iso3' => 'KNA',
                'currency' => 'XCD',
                'languages' => 'en-KN',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'name' => 'North Korea',
                'code' => 'KP',
                'iso3' => 'PRK',
                'currency' => 'KPW',
                'languages' => 'ko-KP',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'name' => 'South Korea',
                'code' => 'KR',
                'iso3' => 'KOR',
                'currency' => 'KRW',
                'languages' => 'ko-KR,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'name' => 'Kuwait',
                'code' => 'KW',
                'iso3' => 'KWT',
                'currency' => 'KWD',
                'languages' => 'ar-KW,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'name' => 'Cayman Islands',
                'code' => 'KY',
                'iso3' => 'CYM',
                'currency' => 'KYD',
                'languages' => 'en-KY',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'name' => 'Kazakhstan',
                'code' => 'KZ',
                'iso3' => 'KAZ',
                'currency' => 'KZT',
                'languages' => 'kk,ru',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'name' => 'Laos',
                'code' => 'LA',
                'iso3' => 'LAO',
                'currency' => 'LAK',
                'languages' => 'lo,fr,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'name' => 'Lebanon',
                'code' => 'LB',
                'iso3' => 'LBN',
                'currency' => 'LBP',
                'languages' => 'ar-LB,fr-LB,en,hy',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'name' => 'Saint Lucia',
                'code' => 'LC',
                'iso3' => 'LCA',
                'currency' => 'XCD',
                'languages' => 'en-LC',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'name' => 'Liechtenstein',
                'code' => 'LI',
                'iso3' => 'LIE',
                'currency' => 'CHF',
                'languages' => 'de-LI',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'name' => 'Sri Lanka',
                'code' => 'LK',
                'iso3' => 'LKA',
                'currency' => 'LKR',
                'languages' => 'si,ta,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'name' => 'Liberia',
                'code' => 'LR',
                'iso3' => 'LBR',
                'currency' => 'LRD',
                'languages' => 'en-LR',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'name' => 'Lesotho',
                'code' => 'LS',
                'iso3' => 'LSO',
                'currency' => 'LSL',
                'languages' => 'en-LS,st,zu,xh',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'name' => 'Lithuania',
                'code' => 'LT',
                'iso3' => 'LTU',
                'currency' => 'EUR',
                'languages' => 'lt,ru,pl',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'name' => 'Luxembourg',
                'code' => 'LU',
                'iso3' => 'LUX',
                'currency' => 'EUR',
                'languages' => 'lb,de-LU,fr-LU',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'name' => 'Latvia',
                'code' => 'LV',
                'iso3' => 'LVA',
                'currency' => 'EUR',
                'languages' => 'lv,ru,lt',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'name' => 'Libya',
                'code' => 'LY',
                'iso3' => 'LBY',
                'currency' => 'LYD',
                'languages' => 'ar-LY,it,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'name' => 'Morocco',
                'code' => 'MA',
                'iso3' => 'MAR',
                'currency' => 'MAD',
                'languages' => 'ar-MA,fr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'name' => 'Monaco',
                'code' => 'MC',
                'iso3' => 'MCO',
                'currency' => 'EUR',
                'languages' => 'fr-MC,en,it',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'name' => 'Moldova',
                'code' => 'MD',
                'iso3' => 'MDA',
                'currency' => 'MDL',
                'languages' => 'ro,ru,gag,tr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'name' => 'Montenegro',
                'code' => 'ME',
                'iso3' => 'MNE',
                'currency' => 'EUR',
                'languages' => 'sr,hu,bs,sq,hr,rom',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'name' => 'Saint Martin',
                'code' => 'MF',
                'iso3' => 'MAF',
                'currency' => 'EUR',
                'languages' => 'fr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'name' => 'Madagascar',
                'code' => 'MG',
                'iso3' => 'MDG',
                'currency' => 'MGA',
                'languages' => 'fr-MG,mg',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'name' => 'Marshall Islands',
                'code' => 'MH',
                'iso3' => 'MHL',
                'currency' => 'USD',
                'languages' => 'mh,en-MH',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'name' => 'North Macedonia',
                'code' => 'MK',
                'iso3' => 'MKD',
                'currency' => 'MKD',
                'languages' => 'mk,sq,tr,rmm,sr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'name' => 'Mali',
                'code' => 'ML',
                'iso3' => 'MLI',
                'currency' => 'XOF',
                'languages' => 'fr-ML,bm',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'name' => 'Myanmar [Burma]',
                'code' => 'MM',
                'iso3' => 'MMR',
                'currency' => 'MMK',
                'languages' => 'my',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            146 => 
            array (
                'id' => 147,
                'name' => 'Mongolia',
                'code' => 'MN',
                'iso3' => 'MNG',
                'currency' => 'MNT',
                'languages' => 'mn,ru',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            147 => 
            array (
                'id' => 148,
                'name' => 'Macao',
                'code' => 'MO',
                'iso3' => 'MAC',
                'currency' => 'MOP',
                'languages' => 'zh,zh-MO,pt',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            148 => 
            array (
                'id' => 149,
                'name' => 'Northern Mariana Islands',
                'code' => 'MP',
                'iso3' => 'MNP',
                'currency' => 'USD',
                'languages' => 'fil,tl,zh,ch-MP,en-MP',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            149 => 
            array (
                'id' => 150,
                'name' => 'Martinique',
                'code' => 'MQ',
                'iso3' => 'MTQ',
                'currency' => 'EUR',
                'languages' => 'fr-MQ',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            150 => 
            array (
                'id' => 151,
                'name' => 'Mauritania',
                'code' => 'MR',
                'iso3' => 'MRT',
                'currency' => 'MRO',
                'languages' => 'ar-MR,fuc,snk,fr,mey,wo',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            151 => 
            array (
                'id' => 152,
                'name' => 'Montserrat',
                'code' => 'MS',
                'iso3' => 'MSR',
                'currency' => 'XCD',
                'languages' => 'en-MS',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            152 => 
            array (
                'id' => 153,
                'name' => 'Malta',
                'code' => 'MT',
                'iso3' => 'MLT',
                'currency' => 'EUR',
                'languages' => 'mt,en-MT',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            153 => 
            array (
                'id' => 154,
                'name' => 'Mauritius',
                'code' => 'MU',
                'iso3' => 'MUS',
                'currency' => 'MUR',
                'languages' => 'en-MU,bho,fr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            154 => 
            array (
                'id' => 155,
                'name' => 'Maldives',
                'code' => 'MV',
                'iso3' => 'MDV',
                'currency' => 'MVR',
                'languages' => 'dv,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            155 => 
            array (
                'id' => 156,
                'name' => 'Malawi',
                'code' => 'MW',
                'iso3' => 'MWI',
                'currency' => 'MWK',
                'languages' => 'ny,yao,tum,swk',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            156 => 
            array (
                'id' => 157,
                'name' => 'Mexico',
                'code' => 'MX',
                'iso3' => 'MEX',
                'currency' => 'MXN',
                'languages' => 'es-MX',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            157 => 
            array (
                'id' => 158,
                'name' => 'Malaysia',
                'code' => 'MY',
                'iso3' => 'MYS',
                'currency' => 'MYR',
                'languages' => 'ms-MY,en,zh,ta,te,ml,pa,th',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            158 => 
            array (
                'id' => 159,
                'name' => 'Mozambique',
                'code' => 'MZ',
                'iso3' => 'MOZ',
                'currency' => 'MZN',
                'languages' => 'pt-MZ,vmw',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            159 => 
            array (
                'id' => 160,
                'name' => 'Namibia',
                'code' => 'NA',
                'iso3' => 'NAM',
                'currency' => 'NAD',
                'languages' => 'en-NA,af,de,hz,naq',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            160 => 
            array (
                'id' => 161,
                'name' => 'New Caledonia',
                'code' => 'NC',
                'iso3' => 'NCL',
                'currency' => 'XPF',
                'languages' => 'fr-NC',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            161 => 
            array (
                'id' => 162,
                'name' => 'Niger',
                'code' => 'NE',
                'iso3' => 'NER',
                'currency' => 'XOF',
                'languages' => 'fr-NE,ha,kr,dje',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            162 => 
            array (
                'id' => 163,
                'name' => 'Norfolk Island',
                'code' => 'NF',
                'iso3' => 'NFK',
                'currency' => 'AUD',
                'languages' => 'en-NF',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            163 => 
            array (
                'id' => 164,
                'name' => 'Nigeria',
                'code' => 'NG',
                'iso3' => 'NGA',
                'currency' => 'NGN',
                'languages' => 'en-NG,ha,yo,ig,ff',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            164 => 
            array (
                'id' => 165,
                'name' => 'Nicaragua',
                'code' => 'NI',
                'iso3' => 'NIC',
                'currency' => 'NIO',
                'languages' => 'es-NI,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            165 => 
            array (
                'id' => 166,
                'name' => 'Netherlands',
                'code' => 'NL',
                'iso3' => 'NLD',
                'currency' => 'EUR',
                'languages' => 'nl-NL,fy-NL',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            166 => 
            array (
                'id' => 167,
                'name' => 'Norway',
                'code' => 'NO',
                'iso3' => 'NOR',
                'currency' => 'NOK',
                'languages' => 'no,nb,nn,se,fi',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            167 => 
            array (
                'id' => 168,
                'name' => 'Nepal',
                'code' => 'NP',
                'iso3' => 'NPL',
                'currency' => 'NPR',
                'languages' => 'ne,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            168 => 
            array (
                'id' => 169,
                'name' => 'Nauru',
                'code' => 'NR',
                'iso3' => 'NRU',
                'currency' => 'AUD',
                'languages' => 'na,en-NR',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            169 => 
            array (
                'id' => 170,
                'name' => 'Niue',
                'code' => 'NU',
                'iso3' => 'NIU',
                'currency' => 'NZD',
                'languages' => 'niu,en-NU',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            170 => 
            array (
                'id' => 171,
                'name' => 'New Zealand',
                'code' => 'NZ',
                'iso3' => 'NZL',
                'currency' => 'NZD',
                'languages' => 'en-NZ,mi',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            171 => 
            array (
                'id' => 172,
                'name' => 'Oman',
                'code' => 'OM',
                'iso3' => 'OMN',
                'currency' => 'OMR',
                'languages' => 'ar-OM,en,bal,ur',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            172 => 
            array (
                'id' => 173,
                'name' => 'Panama',
                'code' => 'PA',
                'iso3' => 'PAN',
                'currency' => 'PAB',
                'languages' => 'es-PA,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            173 => 
            array (
                'id' => 174,
                'name' => 'Peru',
                'code' => 'PE',
                'iso3' => 'PER',
                'currency' => 'PEN',
                'languages' => 'es-PE,qu,ay',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            174 => 
            array (
                'id' => 175,
                'name' => 'French Polynesia',
                'code' => 'PF',
                'iso3' => 'PYF',
                'currency' => 'XPF',
                'languages' => 'fr-PF,ty',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            175 => 
            array (
                'id' => 176,
                'name' => 'Papua New Guinea',
                'code' => 'PG',
                'iso3' => 'PNG',
                'currency' => 'PGK',
                'languages' => 'en-PG,ho,meu,tpi',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            176 => 
            array (
                'id' => 177,
                'name' => 'Philippines',
                'code' => 'PH',
                'iso3' => 'PHL',
                'currency' => 'PHP',
                'languages' => 'tl,en-PH,fil',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            177 => 
            array (
                'id' => 178,
                'name' => 'Pakistan',
                'code' => 'PK',
                'iso3' => 'PAK',
                'currency' => 'PKR',
                'languages' => 'ur-PK,en-PK,pa,sd,ps,brh',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            178 => 
            array (
                'id' => 179,
                'name' => 'Poland',
                'code' => 'PL',
                'iso3' => 'POL',
                'currency' => 'PLN',
                'languages' => 'pl',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            179 => 
            array (
                'id' => 180,
                'name' => 'Saint Pierre and Miquelon',
                'code' => 'PM',
                'iso3' => 'SPM',
                'currency' => 'EUR',
                'languages' => 'fr-PM',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            180 => 
            array (
                'id' => 181,
                'name' => 'Pitcairn Islands',
                'code' => 'PN',
                'iso3' => 'PCN',
                'currency' => 'NZD',
                'languages' => 'en-PN',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            181 => 
            array (
                'id' => 182,
                'name' => 'Puerto Rico',
                'code' => 'PR',
                'iso3' => 'PRI',
                'currency' => 'USD',
                'languages' => 'en-PR,es-PR',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            182 => 
            array (
                'id' => 183,
                'name' => 'Palestine',
                'code' => 'PS',
                'iso3' => 'PSE',
                'currency' => 'ILS',
                'languages' => 'ar-PS',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            183 => 
            array (
                'id' => 184,
                'name' => 'Portugal',
                'code' => 'PT',
                'iso3' => 'PRT',
                'currency' => 'EUR',
                'languages' => 'pt-PT,mwl',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            184 => 
            array (
                'id' => 185,
                'name' => 'Palau',
                'code' => 'PW',
                'iso3' => 'PLW',
                'currency' => 'USD',
                'languages' => 'pau,sov,en-PW,tox,ja,fil,zh',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            185 => 
            array (
                'id' => 186,
                'name' => 'Paraguay',
                'code' => 'PY',
                'iso3' => 'PRY',
                'currency' => 'PYG',
                'languages' => 'es-PY,gn',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            186 => 
            array (
                'id' => 187,
                'name' => 'Qatar',
                'code' => 'QA',
                'iso3' => 'QAT',
                'currency' => 'QAR',
                'languages' => 'ar-QA,es',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            187 => 
            array (
                'id' => 188,
                'name' => 'Réunion',
                'code' => 'RE',
                'iso3' => 'REU',
                'currency' => 'EUR',
                'languages' => 'fr-RE',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            188 => 
            array (
                'id' => 189,
                'name' => 'Romania',
                'code' => 'RO',
                'iso3' => 'ROU',
                'currency' => 'RON',
                'languages' => 'ro,hu,rom',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            189 => 
            array (
                'id' => 190,
                'name' => 'Serbia',
                'code' => 'RS',
                'iso3' => 'SRB',
                'currency' => 'RSD',
                'languages' => 'sr,hu,bs,rom',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            190 => 
            array (
                'id' => 191,
                'name' => 'Russia',
                'code' => 'RU',
                'iso3' => 'RUS',
                'currency' => 'RUB',
                'languages' => 'ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,tut,kbd,krc,ava,sah,nog',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            191 => 
            array (
                'id' => 192,
                'name' => 'Rwanda',
                'code' => 'RW',
                'iso3' => 'RWA',
                'currency' => 'RWF',
                'languages' => 'rw,en-RW,fr-RW,sw',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            192 => 
            array (
                'id' => 193,
                'name' => 'Saudi Arabia',
                'code' => 'SA',
                'iso3' => 'SAU',
                'currency' => 'SAR',
                'languages' => 'ar-SA',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            193 => 
            array (
                'id' => 194,
                'name' => 'Solomon Islands',
                'code' => 'SB',
                'iso3' => 'SLB',
                'currency' => 'SBD',
                'languages' => 'en-SB,tpi',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            194 => 
            array (
                'id' => 195,
                'name' => 'Seychelles',
                'code' => 'SC',
                'iso3' => 'SYC',
                'currency' => 'SCR',
                'languages' => 'en-SC,fr-SC',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            195 => 
            array (
                'id' => 196,
                'name' => 'Sudan',
                'code' => 'SD',
                'iso3' => 'SDN',
                'currency' => 'SDG',
                'languages' => 'ar-SD,en,fia',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            196 => 
            array (
                'id' => 197,
                'name' => 'Sweden',
                'code' => 'SE',
                'iso3' => 'SWE',
                'currency' => 'SEK',
                'languages' => 'sv-SE,se,sma,fi-SE',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            197 => 
            array (
                'id' => 198,
                'name' => 'Singapore',
                'code' => 'SG',
                'iso3' => 'SGP',
                'currency' => 'SGD',
                'languages' => 'cmn,en-SG,ms-SG,ta-SG,zh-SG',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            198 => 
            array (
                'id' => 199,
                'name' => 'Saint Helena',
                'code' => 'SH',
                'iso3' => 'SHN',
                'currency' => 'SHP',
                'languages' => 'en-SH',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            199 => 
            array (
                'id' => 200,
                'name' => 'Slovenia',
                'code' => 'SI',
                'iso3' => 'SVN',
                'currency' => 'EUR',
                'languages' => 'sl,sh',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            200 => 
            array (
                'id' => 201,
                'name' => 'Svalbard and Jan Mayen',
                'code' => 'SJ',
                'iso3' => 'SJM',
                'currency' => 'NOK',
                'languages' => 'no,ru',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            201 => 
            array (
                'id' => 202,
                'name' => 'Slovakia',
                'code' => 'SK',
                'iso3' => 'SVK',
                'currency' => 'EUR',
                'languages' => 'sk,hu',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            202 => 
            array (
                'id' => 203,
                'name' => 'Sierra Leone',
                'code' => 'SL',
                'iso3' => 'SLE',
                'currency' => 'SLL',
                'languages' => 'en-SL,men,tem',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            203 => 
            array (
                'id' => 204,
                'name' => 'San Marino',
                'code' => 'SM',
                'iso3' => 'SMR',
                'currency' => 'EUR',
                'languages' => 'it-SM',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            204 => 
            array (
                'id' => 205,
                'name' => 'Senegal',
                'code' => 'SN',
                'iso3' => 'SEN',
                'currency' => 'XOF',
                'languages' => 'fr-SN,wo,fuc,mnk',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            205 => 
            array (
                'id' => 206,
                'name' => 'Somalia',
                'code' => 'SO',
                'iso3' => 'SOM',
                'currency' => 'SOS',
                'languages' => 'so-SO,ar-SO,it,en-SO',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            206 => 
            array (
                'id' => 207,
                'name' => 'Suriname',
                'code' => 'SR',
                'iso3' => 'SUR',
                'currency' => 'SRD',
                'languages' => 'nl-SR,en,srn,hns,jv',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            207 => 
            array (
                'id' => 208,
                'name' => 'South Sudan',
                'code' => 'SS',
                'iso3' => 'SSD',
                'currency' => 'SSP',
                'languages' => 'en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            208 => 
            array (
                'id' => 209,
                'name' => 'São Tomé and Príncipe',
                'code' => 'ST',
                'iso3' => 'STP',
                'currency' => 'STD',
                'languages' => 'pt-ST',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            209 => 
            array (
                'id' => 210,
                'name' => 'El Salvador',
                'code' => 'SV',
                'iso3' => 'SLV',
                'currency' => 'USD',
                'languages' => 'es-SV',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            210 => 
            array (
                'id' => 211,
                'name' => 'Sint Maarten',
                'code' => 'SX',
                'iso3' => 'SXM',
                'currency' => 'ANG',
                'languages' => 'nl,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            211 => 
            array (
                'id' => 212,
                'name' => 'Syria',
                'code' => 'SY',
                'iso3' => 'SYR',
                'currency' => 'SYP',
                'languages' => 'ar-SY,ku,hy,arc,fr,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            212 => 
            array (
                'id' => 213,
                'name' => 'Swaziland',
                'code' => 'SZ',
                'iso3' => 'SWZ',
                'currency' => 'SZL',
                'languages' => 'en-SZ,ss-SZ',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            213 => 
            array (
                'id' => 214,
                'name' => 'Turks and Caicos Islands',
                'code' => 'TC',
                'iso3' => 'TCA',
                'currency' => 'USD',
                'languages' => 'en-TC',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            214 => 
            array (
                'id' => 215,
                'name' => 'Chad',
                'code' => 'TD',
                'iso3' => 'TCD',
                'currency' => 'XAF',
                'languages' => 'fr-TD,ar-TD,sre',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            215 => 
            array (
                'id' => 216,
                'name' => 'French Southern Territories',
                'code' => 'TF',
                'iso3' => 'ATF',
                'currency' => 'EUR',
                'languages' => 'fr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            216 => 
            array (
                'id' => 217,
                'name' => 'Togo',
                'code' => 'TG',
                'iso3' => 'TGO',
                'currency' => 'XOF',
                'languages' => 'fr-TG,ee,hna,kbp,dag,ha',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            217 => 
            array (
                'id' => 218,
                'name' => 'Thailand',
                'code' => 'TH',
                'iso3' => 'THA',
                'currency' => 'THB',
                'languages' => 'th,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            218 => 
            array (
                'id' => 219,
                'name' => 'Tajikistan',
                'code' => 'TJ',
                'iso3' => 'TJK',
                'currency' => 'TJS',
                'languages' => 'tg,ru',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            219 => 
            array (
                'id' => 220,
                'name' => 'Tokelau',
                'code' => 'TK',
                'iso3' => 'TKL',
                'currency' => 'NZD',
                'languages' => 'tkl,en-TK',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            220 => 
            array (
                'id' => 221,
                'name' => 'East Timor',
                'code' => 'TL',
                'iso3' => 'TLS',
                'currency' => 'USD',
                'languages' => 'tet,pt-TL,id,en',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            221 => 
            array (
                'id' => 222,
                'name' => 'Turkmenistan',
                'code' => 'TM',
                'iso3' => 'TKM',
                'currency' => 'TMT',
                'languages' => 'tk,ru,uz',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            222 => 
            array (
                'id' => 223,
                'name' => 'Tunisia',
                'code' => 'TN',
                'iso3' => 'TUN',
                'currency' => 'TND',
                'languages' => 'ar-TN,fr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            223 => 
            array (
                'id' => 224,
                'name' => 'Tonga',
                'code' => 'TO',
                'iso3' => 'TON',
                'currency' => 'TOP',
                'languages' => 'to,en-TO',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            224 => 
            array (
                'id' => 225,
                'name' => 'Turkey',
                'code' => 'TR',
                'iso3' => 'TUR',
                'currency' => 'TRY',
                'languages' => 'tr-TR,ku,diq,az,av',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            225 => 
            array (
                'id' => 226,
                'name' => 'Trinidad and Tobago',
                'code' => 'TT',
                'iso3' => 'TTO',
                'currency' => 'TTD',
                'languages' => 'en-TT,hns,fr,es,zh',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            226 => 
            array (
                'id' => 227,
                'name' => 'Tuvalu',
                'code' => 'TV',
                'iso3' => 'TUV',
                'currency' => 'AUD',
                'languages' => 'tvl,en,sm,gil',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            227 => 
            array (
                'id' => 228,
                'name' => 'Taiwan',
                'code' => 'TW',
                'iso3' => 'TWN',
                'currency' => 'TWD',
                'languages' => 'zh-TW,zh,nan,hak',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            228 => 
            array (
                'id' => 229,
                'name' => 'Tanzania',
                'code' => 'TZ',
                'iso3' => 'TZA',
                'currency' => 'TZS',
                'languages' => 'sw-TZ,en,ar',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            229 => 
            array (
                'id' => 230,
                'name' => 'Ukraine',
                'code' => 'UA',
                'iso3' => 'UKR',
                'currency' => 'UAH',
                'languages' => 'uk,ru-UA,rom,pl,hu',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            230 => 
            array (
                'id' => 231,
                'name' => 'Uganda',
                'code' => 'UG',
                'iso3' => 'UGA',
                'currency' => 'UGX',
                'languages' => 'en-UG,lg,sw,ar',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            231 => 
            array (
                'id' => 232,
                'name' => 'U.S. Minor Outlying Islands',
                'code' => 'UM',
                'iso3' => 'UMI',
                'currency' => 'USD',
                'languages' => 'en-UM',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            232 => 
            array (
                'id' => 233,
                'name' => 'United States',
                'code' => 'US',
                'iso3' => 'USA',
                'currency' => 'USD',
                'languages' => 'en-US,es-US,haw,fr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            233 => 
            array (
                'id' => 234,
                'name' => 'Uruguay',
                'code' => 'UY',
                'iso3' => 'URY',
                'currency' => 'UYU',
                'languages' => 'es-UY',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            234 => 
            array (
                'id' => 235,
                'name' => 'Uzbekistan',
                'code' => 'UZ',
                'iso3' => 'UZB',
                'currency' => 'UZS',
                'languages' => 'uz,ru,tg',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            235 => 
            array (
                'id' => 236,
                'name' => 'Vatican City',
                'code' => 'VA',
                'iso3' => 'VAT',
                'currency' => 'EUR',
                'languages' => 'la,it,fr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            236 => 
            array (
                'id' => 237,
                'name' => 'Saint Vincent and the Grenadines',
                'code' => 'VC',
                'iso3' => 'VCT',
                'currency' => 'XCD',
                'languages' => 'en-VC,fr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            237 => 
            array (
                'id' => 238,
                'name' => 'Venezuela',
                'code' => 'VE',
                'iso3' => 'VEN',
                'currency' => 'VEF',
                'languages' => 'es-VE',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            238 => 
            array (
                'id' => 239,
                'name' => 'British Virgin Islands',
                'code' => 'VG',
                'iso3' => 'VGB',
                'currency' => 'USD',
                'languages' => 'en-VG',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            239 => 
            array (
                'id' => 240,
                'name' => 'U.S. Virgin Islands',
                'code' => 'VI',
                'iso3' => 'VIR',
                'currency' => 'USD',
                'languages' => 'en-VI',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            240 => 
            array (
                'id' => 241,
                'name' => 'Vietnam',
                'code' => 'VN',
                'iso3' => 'VNM',
                'currency' => 'VND',
                'languages' => 'vi,en,fr,zh,km',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            241 => 
            array (
                'id' => 242,
                'name' => 'Vanuatu',
                'code' => 'VU',
                'iso3' => 'VUT',
                'currency' => 'VUV',
                'languages' => 'bi,en-VU,fr-VU',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            242 => 
            array (
                'id' => 243,
                'name' => 'Wallis and Futuna',
                'code' => 'WF',
                'iso3' => 'WLF',
                'currency' => 'XPF',
                'languages' => 'wls,fud,fr-WF',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            243 => 
            array (
                'id' => 244,
                'name' => 'Samoa',
                'code' => 'WS',
                'iso3' => 'WSM',
                'currency' => 'WST',
                'languages' => 'sm,en-WS',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            244 => 
            array (
                'id' => 245,
                'name' => 'Kosovo',
                'code' => 'XK',
                'iso3' => 'XKX',
                'currency' => 'EUR',
                'languages' => 'sq,sr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            245 => 
            array (
                'id' => 246,
                'name' => 'Yemen',
                'code' => 'YE',
                'iso3' => 'YEM',
                'currency' => 'YER',
                'languages' => 'ar-YE',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            246 => 
            array (
                'id' => 247,
                'name' => 'Mayotte',
                'code' => 'YT',
                'iso3' => 'MYT',
                'currency' => 'EUR',
                'languages' => 'fr-YT',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            247 => 
            array (
                'id' => 248,
                'name' => 'South Africa',
                'code' => 'ZA',
                'iso3' => 'ZAF',
                'currency' => 'ZAR',
                'languages' => 'zu,xh,af,nso,en-ZA,tn,st,ts,ss,ve,nr',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            248 => 
            array (
                'id' => 249,
                'name' => 'Zambia',
                'code' => 'ZM',
                'iso3' => 'ZMB',
                'currency' => 'ZMW',
                'languages' => 'en-ZM,bem,loz,lun,lue,ny,toi',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            249 => 
            array (
                'id' => 250,
                'name' => 'Zimbabwe',
                'code' => 'ZW',
                'iso3' => 'ZWE',
                'currency' => 'ZWL',
                'languages' => 'en-ZW,sn,nr,nd',
                'phone' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}